CREATE TABLE user_balance (
  user_id BIGINT,
  balance INTEGER,
  PRIMARY KEY (user_id)
);

CREATE TABLE user_fish_inventory (
  user_id BIGINT,
  fish TEXT,
  fish_name TEXT
);

CREATE TABLE user_item_inventory (
  user_id BIGINT,
  cfb INT NOT NULL DEFAULT 0,
  ufb INT NOT NULL DEFAULT 0,
  rfb INT NOT NULL DEFAULT 0,
  efb INT NOT NULL DEFAULT 0,
  lfb INT NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id)
);

